version: "3"
services:
  postgresql_server:
    image: postgres:11
    container_name: postgres_server
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=myuser
    - POSTGRES_PASSWORD=mypass
    - POSTGRES_DB=mydata
    volumes:
    - ./backup:/backup



 